In [385]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [386]:
class ACP:

 def __init__(self, df, col_string = True, X_scale = True):
    self.df = df
    self.col_string = col_string
    self.X_scale = X_scale
    self.eigvecs = None
    
 def string(self):
   if self.col_string == True:
     self.df = pd.DataFrame(self.df)
     for i in range(self.df.shape[1]):
       x = (self.df.iloc[:,[i]].dtypes == 'O')
       x = x.bool()

       if x == True:
         self.df = np.delete(np.array(self.df), i, axis=1)
         print(self.df)  
            
   else:
     self.df = pd.DataFrame(self.df)
     self.df = self.df.values
     print(self.df) 
            
 def inercia(self):
   if self.X_scale == True:
     X_std = StandardScaler().fit_transform(self.df)
     self.df = X_std
   else:
     self.df = self.df  

   cov = self.df.T.dot(self.df)/self.df.shape[0]
   eigvals, self.eigvecs = np.linalg.eig(cov)
   varianza_explicada = {i:i/sum(eigvals) for i in eigvals}

   iner = pd.DataFrame({'eigvalues': eigvals,
                        'inercia_acum': np.cumsum(eigvals),
                        'Var_expl': varianza_explicada.values(),
                        'Var_expl_acum':np.cumsum([i for i in varianza_explicada.values()])}) 
   return iner

 def proyec(self):
     for i in range(self.df.shape[1]):
       p = pd.DataFrame((np.dot(self.eigvecs.T, self.df.T)).T)
     for j in range(self.df.shape[1]): 
       p = p.rename(columns = {j : f'CP{[j]}'})
     return p


In [362]:
acp = pd.read_excel('/content/acp_departamentos.xlsx')

In [363]:
del acp['Unnamed: 0']

In [364]:
INTENTO_1 = ACP(df = acp)

In [365]:
INTENTO_1.string() #Sale error pero si transformó la base

[[0.0 54.01720833922807 98.3884866178797 3.858372024230576
  3.858372024230576 1.286124008076859 0.0 70.73682044422723 0.0
  21.8641081373066 105.4621686623024 65.59232441191979 1.286124008076859
  176.8420511105681 0.0 0.0 0.0 86.17030854114954]
 [1.358735893191756 15.81629646456921 38.93770669197274 10.56455323695163
  18.02996730179173 5.870044392496969 11.96145586871619 69.81459819736968
  0.08396682486016471 59.36454517613645 294.0365539648677
  41.81547878036202 46.34968732281092 99.31748711414572
  0.1984670405785711 0.05343343400192299 0.5419676877337903
  128.9272428989256]
 [6.604571791695376 77.46984209718359 54.62159373672392 23.91926000235622
  28.5603104505746 10.88861835928157 9.282100896436743 39.27042686954007
  0.0 43.19746955649408 90.32198179994217 42.6619637355458
  22.84824836045968 86.03793523235598 6.426069851379284 1.249513582212639
  11.24562223991375 68.18774120074686]
 [0.0 40.8117537850901 65.6188982426939 4.801382798245895
  20.00576165935789 20.8059921257

AttributeError: ignored

In [366]:
INTENTO_1.inercia()

eigvalues  inercia_acum  Var_expl  Var_expl_acum
0    4.566025      4.566025  0.253668       0.253668
1    3.708457      8.274482  0.206025       0.459693
2    2.112828     10.387310  0.117379       0.577073
3    1.801209     12.188519  0.100067       0.677140
4    1.439058     13.627577  0.079948       0.757088
5    1.394684     15.022261  0.077482       0.834570
6    0.827216     15.849477  0.045956       0.880526
7    0.607684     16.457161  0.033760       0.914287
8    0.400737     16.857898  0.022263       0.936550
9    0.321609     17.179507  0.017867       0.954417
10   0.247615     17.427122  0.013756       0.968173
11   0.199802     17.626924  0.011100       0.979274
12   0.008507     17.635431  0.000473       0.979746
13   0.036370     17.671801  0.002021       0.981767
14   0.053329     17.725130  0.002963       0.984729
15   0.117420     17.842550  0.006523       0.991253
16   0.086741     17.929291  0.004819       0.996072
17   0.070709     18.000000  0.003928       1.000000

In [367]:
INTENTO_1.proyec()

CP[0]     CP[1]     CP[2]  ...    CP[15]    CP[16]    CP[17]
0  -0.100342 -2.314763 -2.228672  ...  0.194902  0.340619  0.135711
1   1.064097  0.113578  1.974590  ... -0.103452 -0.315433  0.395975
2   0.605066  8.127096 -2.243102  ...  0.116777 -0.010521  0.034154
3   7.588479 -0.138221  0.432225  ... -0.245063 -0.147008  0.082205
4  -0.771822 -1.004602  1.563175  ...  0.210109  0.022016 -0.602925
5  -1.170507 -0.864814  0.500206  ...  0.163398 -0.182454 -0.001914
6   0.086969 -1.631202 -1.196964  ...  0.491063 -0.363432  0.510821
7  -1.451921 -1.625057 -0.482609  ...  0.440432 -0.431416 -0.218484
8  -0.499531  1.431537 -0.632299  ... -0.272882 -0.102132 -0.459292
9   1.492595 -0.338706 -2.155883  ...  0.015155 -0.421444 -0.070887
10  0.852734  3.068359  2.093300  ...  0.314824  0.116387  0.171704
11 -0.931612  0.429650  0.654751  ... -0.793890  0.182126 -0.145605
12 -2.671126  1.136407  1.040448  ...  0.128914  0.352221 -0.089054
13  3.920250 -2.293586  2.316495  ... -0.248512 -0.247232 -0.214733
14 -2.363139 -0.004425  0.367722  ... -0.340265 -0.397027  0.128397
15 -1.032098 -1.698583 -1.751946  ... -0.881277 -0.171418  0.387459
16 -0.902567  0.738743 -2.603427  ...  0.056399 -0.251473 -0.249809
17  0.631023 -0.363450 -0.571855  ...  0.278857 -0.059269 -0.466055
18 -1.880384  0.841781  2.122957  ...  0.036699  0.222922 -0.167211
19 -1.395568 -0.360013  0.512413  ... -0.046022 -0.137658 -0.142811
20  2.349352  0.460853 -2.182442  ... -0.147633  0.725469  0.129046
21 -0.795547  0.530552  1.221109  ...  0.312938 -0.276034  0.019683
22 -0.751439  1.056063  0.710791  ... -0.553335  0.206855 -0.106601
23 -1.965797  1.497217  0.064201  ... -0.258002 -0.499709  0.251091
24  1.200626 -1.011131 -0.387281  ...  0.562285  0.061233  0.103761
25  0.798733 -1.582434 -0.320495  ... -0.398153  0.281305  0.076334
26  0.757924 -1.565854 -0.033263  ...  0.029774  0.408294 -0.104664
27 -1.381579 -0.751540  0.899477  ...  0.360795  0.411155  0.540681
28  2.097665 -0.838533 -1.854946  ...  0.348392  0.116968 -0.219102
29  2.400659  1.552619  2.523757  ...  0.191943  0.133761  0.179941
30 -2.184286 -1.834503 -0.379142  ... -0.062442  0.268533 -0.160778
31 -3.596907 -0.763040  0.026709  ...  0.097270  0.163796  0.272959

[32 rows x 18 columns]

In [368]:
from sklearn.datasets import load_iris
X = load_iris()['data']

In [369]:
INTENTO_2 = ACP(df = X, col_string=False, X_scale= True)

In [370]:
INTENTO_2.string() 

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [371]:
INTENTO_2.inercia()

eigvalues  inercia_acum  Var_expl  Var_expl_acum
0   2.918498      2.918498  0.729624       0.729624
1   0.914030      3.832528  0.228508       0.958132
2   0.146757      3.979285  0.036689       0.994821
3   0.020715      4.000000  0.005179       1.000000

In [372]:
INTENTO_2.proyec()

CP[0]     CP[1]     CP[2]     CP[3]
0   -2.264703 -0.480027 -0.127706  0.024168
1   -2.080961  0.674134 -0.234609  0.103007
2   -2.364229  0.341908  0.044201  0.028377
3   -2.299384  0.597395  0.091290 -0.065956
4   -2.389842 -0.646835  0.015738 -0.035923
..        ...       ...       ...       ...
145  1.870503 -0.386966  0.256274  0.389257
146  1.564580  0.896687 -0.026371  0.220192
147  1.521170 -0.269069  0.180178  0.119171
148  1.372788 -1.011254  0.933395  0.026129
149  0.960656  0.024332  0.528249 -0.163078

[150 rows x 4 columns]

In [373]:
del acp['DEPARTAMENTO']

In [374]:
acp

ABIGEATO    AMENAZAS  ...  TERRORISMO  VIOLENCIA_INTRAFAMILIAR
0    0.000000   54.017208  ...    0.000000                86.170309
1    1.358736   15.816296  ...    0.541968               128.927243
2    6.604572   77.469842  ...   11.245622                68.187741
3    0.000000   40.811754  ...    0.000000               123.235492
4    1.383545   33.887370  ...    0.000000                59.909384
5    5.608980   43.534136  ...    0.000000                79.746089
6    5.240026   64.220780  ...    0.040620               148.304913
7    1.487588   30.941821  ...    0.000000                69.420753
8    2.462193   75.589326  ...    0.246219                61.801045
9   24.733820   32.900647  ...    0.000000                82.251618
10   3.077637   80.661144  ...    0.338202               104.639656
11  11.258402   66.033322  ...    0.000000                50.622885
12   0.370416   49.357976  ...    0.185208                23.521437
13   2.064917   38.751149  ...    0.009365               203.518451
14   3.926038   66.051440  ...    0.000000                56.595771
15   3.031957   63.671093  ...    0.000000                89.948052
16   2.951036  111.549176  ...    0.000000                87.940885
17   4.676915   69.344261  ...    0.000000               105.365501
18   7.493213   49.433642  ...    0.000000                18.436538
19   6.120251   46.405901  ...    0.036001                58.034377
20  10.882737  114.482595  ...    0.380183               142.806225
21   1.411926   68.631862  ...    0.306940               101.106152
22   0.702713   59.538944  ...    0.127766                84.613016
23   0.706696   79.149930  ...    0.141339                65.157353
24   2.920481   39.609021  ...    0.273795                61.330096
25   1.469799   22.571918  ...    0.000000               104.303257
26   3.106024   48.020479  ...    0.000000               116.777582
27   7.858047   52.638151  ...    0.000000                63.994644
28   9.098990   69.609148  ...    0.037444               119.747205
29   1.442275   78.670568  ...    0.077661               107.183241
30   0.000000    8.192692  ...    0.000000               106.504998
31   4.520837   18.083346  ...    0.000000                26.220852

[32 rows x 18 columns]

In [375]:
INTENTO_3 = ACP(df = acp, col_string=False, X_scale= True)

In [376]:
INTENTO_3.string() 

[[0.00000000e+00 5.40172083e+01 9.83884866e+01 3.85837202e+00
  3.85837202e+00 1.28612401e+00 0.00000000e+00 7.07368204e+01
  0.00000000e+00 2.18641081e+01 1.05462169e+02 6.55923244e+01
  1.28612401e+00 1.76842051e+02 0.00000000e+00 0.00000000e+00
  0.00000000e+00 8.61703085e+01]
 [1.35873589e+00 1.58162965e+01 3.89377067e+01 1.05645532e+01
  1.80299673e+01 5.87004439e+00 1.19614559e+01 6.98145982e+01
  8.39668249e-02 5.93645452e+01 2.94036554e+02 4.18154788e+01
  4.63496873e+01 9.93174871e+01 1.98467041e-01 5.34334340e-02
  5.41967688e-01 1.28927243e+02]
 [6.60457179e+00 7.74698421e+01 5.46215937e+01 2.39192600e+01
  2.85603105e+01 1.08886184e+01 9.28210090e+00 3.92704269e+01
  0.00000000e+00 4.31974696e+01 9.03219818e+01 4.26619637e+01
  2.28482484e+01 8.60379352e+01 6.42606985e+00 1.24951358e+00
  1.12456222e+01 6.81877412e+01]
 [0.00000000e+00 4.08117538e+01 6.56188982e+01 4.80138280e+00
  2.00057617e+01 2.08059921e+01 8.00230466e-01 9.60276560e+01
  8.00230466e-01 5.44156717e+01 3

In [377]:
INTENTO_3.inercia() 

eigvalues  inercia_acum  Var_expl  Var_expl_acum
0    4.566025      4.566025  0.253668       0.253668
1    3.708457      8.274482  0.206025       0.459693
2    2.112828     10.387310  0.117379       0.577073
3    1.801209     12.188519  0.100067       0.677140
4    1.439058     13.627577  0.079948       0.757088
5    1.394684     15.022261  0.077482       0.834570
6    0.827216     15.849477  0.045956       0.880526
7    0.607684     16.457161  0.033760       0.914287
8    0.400737     16.857898  0.022263       0.936550
9    0.321609     17.179507  0.017867       0.954417
10   0.247615     17.427122  0.013756       0.968173
11   0.199802     17.626924  0.011100       0.979274
12   0.008507     17.635431  0.000473       0.979746
13   0.036370     17.671801  0.002021       0.981767
14   0.053329     17.725130  0.002963       0.984729
15   0.117420     17.842550  0.006523       0.991253
16   0.086741     17.929291  0.004819       0.996072
17   0.070709     18.000000  0.003928       1.000000

In [378]:
INTENTO_3.proyec() 

CP[0]     CP[1]     CP[2]  ...    CP[15]    CP[16]    CP[17]
0  -0.100342 -2.314763 -2.228672  ...  0.194902  0.340619  0.135711
1   1.064097  0.113578  1.974590  ... -0.103452 -0.315433  0.395975
2   0.605066  8.127096 -2.243102  ...  0.116777 -0.010521  0.034154
3   7.588479 -0.138221  0.432225  ... -0.245063 -0.147008  0.082205
4  -0.771822 -1.004602  1.563175  ...  0.210109  0.022016 -0.602925
5  -1.170507 -0.864814  0.500206  ...  0.163398 -0.182454 -0.001914
6   0.086969 -1.631202 -1.196964  ...  0.491063 -0.363432  0.510821
7  -1.451921 -1.625057 -0.482609  ...  0.440432 -0.431416 -0.218484
8  -0.499531  1.431537 -0.632299  ... -0.272882 -0.102132 -0.459292
9   1.492595 -0.338706 -2.155883  ...  0.015155 -0.421444 -0.070887
10  0.852734  3.068359  2.093300  ...  0.314824  0.116387  0.171704
11 -0.931612  0.429650  0.654751  ... -0.793890  0.182126 -0.145605
12 -2.671126  1.136407  1.040448  ...  0.128914  0.352221 -0.089054
13  3.920250 -2.293586  2.316495  ... -0.248512 -0.247232 -0.214733
14 -2.363139 -0.004425  0.367722  ... -0.340265 -0.397027  0.128397
15 -1.032098 -1.698583 -1.751946  ... -0.881277 -0.171418  0.387459
16 -0.902567  0.738743 -2.603427  ...  0.056399 -0.251473 -0.249809
17  0.631023 -0.363450 -0.571855  ...  0.278857 -0.059269 -0.466055
18 -1.880384  0.841781  2.122957  ...  0.036699  0.222922 -0.167211
19 -1.395568 -0.360013  0.512413  ... -0.046022 -0.137658 -0.142811
20  2.349352  0.460853 -2.182442  ... -0.147633  0.725469  0.129046
21 -0.795547  0.530552  1.221109  ...  0.312938 -0.276034  0.019683
22 -0.751439  1.056063  0.710791  ... -0.553335  0.206855 -0.106601
23 -1.965797  1.497217  0.064201  ... -0.258002 -0.499709  0.251091
24  1.200626 -1.011131 -0.387281  ...  0.562285  0.061233  0.103761
25  0.798733 -1.582434 -0.320495  ... -0.398153  0.281305  0.076334
26  0.757924 -1.565854 -0.033263  ...  0.029774  0.408294 -0.104664
27 -1.381579 -0.751540  0.899477  ...  0.360795  0.411155  0.540681
28  2.097665 -0.838533 -1.854946  ...  0.348392  0.116968 -0.219102
29  2.400659  1.552619  2.523757  ...  0.191943  0.133761  0.179941
30 -2.184286 -1.834503 -0.379142  ... -0.062442  0.268533 -0.160778
31 -3.596907 -0.763040  0.026709  ...  0.097270  0.163796  0.272959

[32 rows x 18 columns]

In [387]:
import statsmodels.api as sm
USArrests = sm.datasets.get_rdataset("USArrests", "datasets")
datos = USArrests.data

In [388]:
datos

Murder  Assault  UrbanPop  Rape
Alabama           13.2      236        58  21.2
Alaska            10.0      263        48  44.5
Arizona            8.1      294        80  31.0
Arkansas           8.8      190        50  19.5
California         9.0      276        91  40.6
Colorado           7.9      204        78  38.7
Connecticut        3.3      110        77  11.1
Delaware           5.9      238        72  15.8
Florida           15.4      335        80  31.9
Georgia           17.4      211        60  25.8
Hawaii             5.3       46        83  20.2
Idaho              2.6      120        54  14.2
Illinois          10.4      249        83  24.0
Indiana            7.2      113        65  21.0
Iowa               2.2       56        57  11.3
Kansas             6.0      115        66  18.0
Kentucky           9.7      109        52  16.3
Louisiana         15.4      249        66  22.2
Maine              2.1       83        51   7.8
Maryland          11.3      300        67  27.8
Massachusetts      4.4      149        85  16.3
Michigan          12.1      255        74  35.1
Minnesota          2.7       72        66  14.9
Mississippi       16.1      259        44  17.1
Missouri           9.0      178        70  28.2
Montana            6.0      109        53  16.4
Nebraska           4.3      102        62  16.5
Nevada            12.2      252        81  46.0
New Hampshire      2.1       57        56   9.5
New Jersey         7.4      159        89  18.8
New Mexico        11.4      285        70  32.1
New York          11.1      254        86  26.1
North Carolina    13.0      337        45  16.1
North Dakota       0.8       45        44   7.3
Ohio               7.3      120        75  21.4
Oklahoma           6.6      151        68  20.0
Oregon             4.9      159        67  29.3
Pennsylvania       6.3      106        72  14.9
Rhode Island       3.4      174        87   8.3
South Carolina    14.4      279        48  22.5
South Dakota       3.8       86        45  12.8
Tennessee         13.2      188        59  26.9
Texas             12.7      201        80  25.5
Utah               3.2      120        80  22.9
Vermont            2.2       48        32  11.2
Virginia           8.5      156        63  20.7
Washington         4.0      145        73  26.2
West Virginia      5.7       81        39   9.3
Wisconsin          2.6       53        66  10.8
Wyoming            6.8      161        60  15.6

In [389]:
INTENTO_4 = ACP(df = datos, col_string=True, X_scale= True)

In [390]:
INTENTO_4.string()

In [391]:
INTENTO_4.inercia()

eigvalues  inercia_acum  Var_expl  Var_expl_acum
0   2.480242      2.480242  0.620060       0.620060
1   0.989765      3.470007  0.247441       0.867502
2   0.173430      3.643437  0.043358       0.910859
3   0.356563      4.000000  0.089141       1.000000

In [392]:
INTENTO_4.proyec()

CP[0]     CP[1]     CP[2]     CP[3]
0   0.985566  1.133392  0.156267 -0.444269
1   1.950138  1.073213 -0.438583  2.040003
2   1.763164 -0.745957 -0.834653  0.054781
3  -0.141420  1.119797 -0.182811  0.114574
4   2.523980 -1.542934 -0.341996  0.598557
5   1.514563 -0.987555  0.001465  1.095007
6  -1.358647 -1.088928 -0.118469 -0.643258
7   0.047709 -0.325359 -0.881978 -0.718633
8   3.013042  0.039229 -0.096285 -0.576829
9   1.639283  1.278942  1.076797 -0.342460
10 -0.912657 -1.570460  0.902807  0.050782
11 -1.639800  0.210973 -0.499104  0.259801
12  1.378911 -0.681841 -0.122021 -0.677496
13 -0.505461 -0.151563  0.424666  0.228055
14 -2.253646 -0.104054  0.017556  0.164564
15 -0.796881 -0.270165  0.206496  0.025553
16 -0.750859  0.958440  0.670557 -0.028369
17  1.564818  0.871055  0.454728 -0.783480
18 -2.396829  0.376392 -0.330460 -0.065682
19  1.763369  0.427655 -0.559070 -0.157250
20 -0.486166 -1.474496 -0.179599 -0.609497
21  2.108441 -0.155397  0.102372  0.384869
22 -1.692682 -0.632261  0.067317  0.153070
23  0.996494  2.393796  0.215508 -0.740808
24  0.696787 -0.263355  0.225824  0.377444
25 -1.185452  0.536874  0.123742  0.246889
26 -1.265637 -0.193954  0.015893  0.175574
27  2.874395 -0.775600  0.314515  1.163380
28 -2.383915 -0.018082 -0.033137  0.036855
29  0.181566 -1.449506  0.243383 -0.764454
30  1.980024  0.142849 -0.339534  0.183692
31  1.682577 -0.823184 -0.013484 -0.643075
32  1.123379  2.228003 -0.954382 -0.863572
33 -2.992226  0.599119 -0.253987  0.301277
34 -0.225965 -0.742238  0.473916 -0.031139
35 -0.311783 -0.287854  0.010332 -0.015310
36  0.059122 -0.541411 -0.237781  0.939833
37 -0.888416 -0.571100  0.359061 -0.400629
38 -0.863772 -1.491978 -0.613569 -1.369946
39  1.320724  1.933405 -0.131467 -0.300538
40 -1.987775  0.823343 -0.109572  0.389293
41  0.999742  0.860251  0.652864  0.188083
42  1.355138 -0.412481  0.643195 -0.492069
43 -0.550565 -1.471505 -0.082314  0.293728
44 -2.801412  1.402288 -0.144890  0.841263
45 -0.096335  0.199735  0.211371  0.011713
46 -0.216903 -0.970124 -0.220848  0.624871
47 -2.108585  1.424847  0.131909  0.104775
48 -2.079714 -0.611269  0.184104 -0.138865
49 -0.629427  0.321013 -0.166652 -0.240659

In [44]:
#AQUI NO SALE EL ERROR
acp = pd.DataFrame(acp)
for i in range(acp.shape[1]):
  x = (acp.iloc[:,[i]].dtypes == 'O')
  x = x.bool()
  
  if x == True:
    df = np.delete(np.array(acp), i, axis=1)  
    print(df)      

[[0.0 54.01720833922807 98.3884866178797 3.858372024230576
  3.858372024230576 1.286124008076859 0.0 70.73682044422723 0.0
  21.8641081373066 105.4621686623024 65.59232441191979 1.286124008076859
  176.8420511105681 0.0 0.0 0.0 86.17030854114954]
 [1.358735893191756 15.81629646456921 38.93770669197274 10.56455323695163
  18.02996730179173 5.870044392496969 11.96145586871619 69.81459819736968
  0.08396682486016471 59.36454517613645 294.0365539648677
  41.81547878036202 46.34968732281092 99.31748711414572
  0.1984670405785711 0.05343343400192299 0.5419676877337903
  128.9272428989256]
 [6.604571791695376 77.46984209718359 54.62159373672392 23.91926000235622
  28.5603104505746 10.88861835928157 9.282100896436743 39.27042686954007
  0.0 43.19746955649408 90.32198179994217 42.6619637355458
  22.84824836045968 86.03793523235598 6.426069851379284 1.249513582212639
  11.24562223991375 68.18774120074686]
 [0.0 40.8117537850901 65.6188982426939 4.801382798245895
  20.00576165935789 20.8059921257